(()=>{
"use strict";
const API="https://hehwhwhwhuuu.yaqubpapp1.workers.dev";let me=null;
const q=s=>document.querySelector(s),esc=s=>String(s??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
async function api(path,opt={}){opt.credentials="include";opt.headers={"Content-Type":"application/json",...(opt.headers||{})};const r=await fetch(API+path,opt);let d={};try{d=await r.json()}catch{}return{r,d}}
const badge=u=>u?.role==="owner"?'<span class="yb owner">♛ OWNER</span>':u?.role==="admin"?'<span class="yb admin">ADMIN</span>':'';
function profile(u){let m=q("#ybUserProfile");if(!m){m=document.createElement("div");m.id="ybUserProfile";m.className="modal";document.body.appendChild(m)}m.className="modal show";m.innerHTML=`<div class="modalBox small glass"><div class="mh"><h2>👤 Profile</h2><button class="close" id="ybPC">✕</button></div><div class="mb"><div class="ybProfile"><img src="${esc(u.pfp||'https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f464.svg')}"><div><div style="font-size:20px;font-weight:900">${esc(u.displayName||u.username)} ${badge(u)}</div><div class="muted">@${esc(u.username)}</div><div class="ybBio">${esc(u.bio||"No bio yet.")}</div></div></div><div class="mini-actions" id="ybActions"></div></div></div>`;q("#ybPC",m).onclick=()=>m.classList.remove("show");const a=q("#ybActions");if(me&&me.role==="owner"&&u.id!==me.id){button(a,u.verified?"↩ Unverify":"✅ Verify",u.verified?"unverify":"verify",u.id);button(a,u.status==="blocked"?"✅ Unblock":"🚫 Block",u.status==="blocked"?"unblock":"block",u.id);button(a,u.status==="banned"?"♻️ Unban":"🔨 Ban",u.status==="banned"?"unblock":"ban",u.id);button(a,"🗑️ Delete Account","delete",u.id)}else if(me&&me.role==="admin"&&u.role==="user"){button(a,u.verified?"↩ Unverify":"✅ Verify",u.verified?"unverify":"verify",u.id);button(a,u.status==="blocked"?"Unblock":"🚫 Block",u.status==="blocked"?"unblock":"block",u.id)}}
function button(a,text,action,id){const b=document.createElement("button");b.textContent=text;b.onclick=()=>act(action,id);a.appendChild(b)}
async function act(action,id){if(action==="delete"&&!confirm("Delete this account permanently?"))return;const map={verify:"/api/admin/verify",unverify:"/api/admin/unverify",block:"/api/admin/block",unblock:"/api/admin/unblock",ban:"/api/admin/ban",delete:"/api/admin/delete"};const x=await api(map[action],{method:"POST",body:JSON.stringify({userId:id})});if(!x.r.ok||!x.d.success)return alert(x.d.error||"Action failed");q("#ybUserProfile")?.classList.remove("show");load()}
async function load(){const list=q("#usersList");if(!list)return;const x=await api("/api/me");if(!x.r.ok||!x.d.success)return;me=x.d.user;const r=await api("/api/admin/users");if(!r.r.ok||!r.d.success)return;list.innerHTML="";(r.d.users||[]).forEach(u=>{const i=document.createElement("div");i.className="item userClick";i.innerHTML=`<div class="top"><strong>@${esc(u.username)} ${badge(u)}</strong><span>${esc(u.status)}</span></div><div class="meta">${esc(u.displayName||"")}</div><div class="meta">Role: ${esc(u.role)} • Verified: ${u.verified?"Yes":"No"}</div><div class="mini-actions"><button>View Profile</button></div>`;i.onclick=e=>{if(!e.target.closest("button"))profile(u)};i.querySelector("button").onclick=()=>profile(u);list.appendChild(i)})}
function hook(){const nav=q("#adminNav");if(nav)nav.addEventListener("click",()=>setTimeout(load,150));const tab=[...document.querySelectorAll(".tab")].find(x=>x.dataset.tab==="users");if(tab)tab.addEventListener("click",()=>setTimeout(load,50))}hook();
})();
