(()=>{
"use strict";
const API="https://hehwhwhwhuuu.yaqubpapp1.workers.dev";
let me=null,ws=null,muted=false;
const q=s=>document.querySelector(s),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
async function api(path,opt={}){opt.credentials="include";opt.headers={"Content-Type":"application/json",...(opt.headers||{})};const r=await fetch(API+path,opt);let data={};try{data=await r.json()}catch{}return{r,data}}
function roleBadge(u){return u?.role==="owner"?'<span class="yb owner">♛ OWNER</span>':u?.role==="admin"?'<span class="yb admin">ADMIN</span>':""}
function style(){const s=document.createElement("style");s.textContent=`.yb{display:inline-flex;align-items:center;gap:5px;margin-left:6px;padding:3px 7px;border-radius:8px;font-size:10px;font-weight:900}.yb.admin{color:#ffd34f;background:#6b4b001c;border:1px solid #f0b90b55}.yb.owner{color:#ff6670;background:#ff33401c;border:1px solid #ff536055;box-shadow:0 0 14px #ff334044}.accountDock{position:fixed;left:14px;bottom:12px;z-index:9999;display:flex;align-items:center;gap:9px;padding:8px 11px;min-width:165px;border:1px solid rgba(255,255,255,.1);border-radius:15px;background:#0a0e16eF;backdrop-filter:blur(15px);box-shadow:0 18px 50px #0007;cursor:pointer}.accountDock img{width:38px;height:38px;border-radius:50%;object-fit:cover;background:#182033}.accountDock strong{display:block;max-width:130px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.accountDock small{color:#8993a8}.ybProfile{display:flex;gap:13px;align-items:center;padding:14px;border:1px solid rgba(255,255,255,.08);border-radius:16px;background:#ffffff05;margin-bottom:13px}.ybProfile img{width:72px;height:72px;border-radius:50%;object-fit:cover;background:#182033}.ybBio{color:#929caf;white-space:pre-wrap;line-height:1.4;margin-top:4px}.userClick{cursor:pointer}.userClick:hover{border-color:#7289da66;background:#7289da0d}.btn,.nav,.tab,.close,.mini-actions button{transition:transform .15s ease,filter .15s ease,box-shadow .15s ease}.btn:active,.nav:active,.tab:active,.close:active,.mini-actions button:active{transform:scale(1.04);filter:brightness(1.16)}.forcedModal{pointer-events:auto}.forcedModal .close{display:none!important}.banOverlay{position:fixed;inset:0;z-index:30000;display:flex;align-items:center;justify-content:center;background:#0008;backdrop-filter:blur(18px)}.banCard{width:min(460px,calc(100% - 32px));padding:34px;text-align:center;border-radius:25px;background:linear-gradient(180deg,#25151a,#0f0a0d);border:1px solid #ff4b6755;box-shadow:0 35px 100px #000b;animation:ybPop .28s cubic-bezier(.2,.8,.2,1)}.banCard h2{font-size:32px;margin:8px 0}.banCard p{color:#aab2c2;line-height:1.5}@keyframes ybPop{from{opacity:0;transform:translateY(15px) scale(.92)}to{opacity:1;transform:none}}`;
document.head.appendChild(s)}
function getModal(){let m=q("#ybAccountModal");if(!m){m=document.createElement("div");m.id="ybAccountModal";m.className="modal";m.innerHTML='<div class="modalBox small glass"><div class="mh"><h2>👤 Profile</h2><button class="close" data-yb-close>✕</button></div><div class="mb"><div id="ybAccount"></div></div></div>';document.body.appendChild(m);m.querySelector("[data-yb-close]").onclick=()=>{if(!m.classList.contains("forcedModal"))m.classList.remove("show")}}return m}
function openAccount(force=false){const m=getModal();m.classList.toggle("forcedModal",force);m.classList.add("show");renderAccount()}
function renderAccount(){const m=getModal(),box=q("#ybAccount",m);if(!me){box.innerHTML='<div class="form"><input id="ybU" placeholder="Username" autocomplete="username"><input id="ybD" placeholder="Display name"><small class="muted" style="font-size:11px;text-align:center">This is to authenticate you, only admins see this</small><input id="ybR" placeholder="Real name"><input id="ybP" type="password" placeholder="Password"><button id="ybSignup" class="btn primary">Create Account</button><button id="ybLoginSwitch" class="btn secondary">Already have an account? Login</button></div>';q("#ybSignup",m).onclick=signup;q("#ybLoginSwitch",m).onclick=loginForm;return}box.innerHTML=`<div class="ybProfile"><img src="${esc(me.pfp||'https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f464.svg')}"><div><div style="font-size:20px;font-weight:900">${esc(me.displayName||me.username)} ${roleBadge(me)}</div><div class="muted">@${esc(me.username)}</div><div class="ybBio">${esc(me.bio||"No bio yet.")}</div></div></div><div class="profileEdit"><input id="ybDisplay" value="${esc(me.displayName||"")}" placeholder="Display name"><input id="ybPfp" value="${esc(me.pfp||"")}" placeholder="Profile picture URL"><textarea id="ybBio" maxlength="500" placeholder="Bio">${esc(me.bio||"")}</textarea><button id="ybSave" class="btn primary">Save Profile</button><button id="ybLogout" class="btn secondary">Log Out</button></div>`;q("#ybSave",m).onclick=saveProfile;q("#ybLogout",m).onclick=logout}
function loginForm(){const m=getModal();q("#ybAccount",m).innerHTML='<div class="form"><input id="ybLU" placeholder="Username"><input id="ybLP" type="password" placeholder="Password"><button id="ybLogin" class="btn primary">Login</button><button id="ybBack" class="btn secondary">Create an account</button></div>';q("#ybLogin",m).onclick=login;q("#ybBack",m).onclick=renderAccount}
async function signup(){const b=q("#ybSignup");b.disabled=true;try{const x=await api("/api/register",{method:"POST",body:JSON.stringify({username:q("#ybU").value,displayName:q("#ybD").value,realName:q("#ybR").value,password:q("#ybP").value})});if(!x.r.ok||!x.data.success)throw Error(x.data.error||"Signup failed");me=x.data.user;openAccount(false);q("#ybAccountModal").classList.remove("show");syncDock()}catch(e){alert(e.message)}finally{b.disabled=false}}
async function login(){const x=await api("/api/login",{method:"POST",body:JSON.stringify({username:q("#ybLU").value,password:q("#ybLP").value})});if(x.r.status===403&&x.data.errorCode==="BANNED")return banned();if(!x.r.ok||!x.data.success)return alert(x.data.error||"Login failed");me=x.data.user;getModal().classList.remove("show");syncDock()}
async function saveProfile(){const x=await api("/api/profile",{method:"POST",body:JSON.stringify({displayName:q("#ybDisplay").value,pfp:q("#ybPfp").value,bio:q("#ybBio").value})});if(!x.r.ok||!x.data.success)return alert(x.data.error||"Could not save profile");me=x.data.user;renderAccount();syncDock()}
async function logout(){await api("/api/logout",{method:"POST"});me=null;syncDock();location.reload()}
function syncDock(){let d=q("#accountDock");if(!d){d=document.createElement("div");d.id="accountDock";d.className="accountDock";d.onclick=()=>openAccount(false);document.body.appendChild(d)}d.innerHTML=`<img src="${esc(me?.pfp||'https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f464.svg')}"><div><strong>${esc(me?.displayName||"Account")}</strong><small>${me?"@"+esc(me.username):"Log in"}</small></div>`}
function banned(){const o=document.createElement("div");o.className="banOverlay";o.innerHTML='<div class="banCard"><div style="font-size:55px">⛔</div><h2>You have been banned</h2><p>This account cannot access yaprxy.</p></div>';document.body.appendChild(o)}
async function boot(){style();syncDock();const x=await api("/api/me");if(x.r.ok&&x.data.success){me=x.data.user;syncDock();return}const enter=q("#enter");if(enter){enter.onclick=async()=>{const pass=q("#accessPass")?.value.trim().toLowerCase();if(pass!=="yaqubraphinha"){if(q("#error"))q("#error").style.display="block";return}q("#access").style.display="none";q("#app").style.display="block";openAccount(true)}}}
boot();
})();
