import { DurableObject } from "cloudflare:workers";
const MAX_HISTORY=200,MAX_MESSAGE=1000;
const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{"Content-Type":"application/json","Cache-Control":"no-store"}});
export class SocialRoom extends DurableObject{
 constructor(ctx,env){super(ctx,env);this.sessions=new Map();for(const ws of ctx.getWebSockets()){const a=ws.deserializeAttachment();if(a)this.sessions.set(ws,a)}}
 async fetch(request){if(request.headers.get("Upgrade")?.toLowerCase()!=="websocket")return json({success:false,error:"WebSocket required"},400);const [client,server]=Object.values(new WebSocketPair());const user={id:request.headers.get("X-Social-User-Id")||"",username:request.headers.get("X-Social-Username")||"user",displayName:request.headers.get("X-Social-Display-Name")||"User",pfp:request.headers.get("X-Social-Pfp")||"",role:request.headers.get("X-Social-Role")||"user",status:"online"};const room=request.headers.get("X-Social-Room")||"global";const a={user,room};this.ctx.acceptWebSocket(server);server.serializeAttachment(a);this.sessions.set(server,a);if(room!=="presence"){const h=await this.ctx.storage.get("messages")||[];server.send(JSON.stringify({type:"history",messages:h}))}this.broadcast({type:"presence",action:"online",user},server);return new Response(null,{status:101,webSocket:client})}
 async webSocketMessage(ws,message){const s=this.sessions.get(ws)||ws.deserializeAttachment();if(!s)return;let d;try{d=JSON.parse(typeof message==="string"?message:new TextDecoder().decode(message))}catch{return}
  if(s.room==="presence"&&d.type==="status"){const allowed=["online","idle","dnd"];if(!allowed.includes(d.status))return;s.user.status=d.status;ws.serializeAttachment(s);this.broadcast({type:"presence",action:"status",user:s.user},ws);return}
  if(d.type==="typing"){this.broadcast({type:"typing",user:s.user,typing:!!d.typing},ws);return}if(s.room==="presence")return;const h=await this.ctx.storage.get("messages")||[];
  if(d.type==="chat"){const text=String(d.text||"").trim().slice(0,MAX_MESSAGE);if(!text)return;const m={id:crypto.randomUUID(),userId:s.user.id,username:s.user.username,displayName:s.user.displayName,pfp:s.user.pfp,role:s.user.role,text,time:new Date().toISOString(),reactions:{}};h.push(m);while(h.length>MAX_HISTORY)h.shift();await this.ctx.storage.put("messages",h);this.broadcast({type:"message",...m});return}
  if(d.type==="edit"){const m=h.find(x=>x.id===d.id);if(!m||m.userId!==s.user.id)return;const text=String(d.text||"").trim().slice(0,MAX_MESSAGE);if(!text)return;m.text=text;m.edited=true;await this.ctx.storage.put("messages",h);this.broadcast({type:"message:update",message:m});return}
  if(d.type==="delete"){const i=h.findIndex(x=>x.id===d.id);if(i<0||h[i].userId!==s.user.id)return;h.splice(i,1);await this.ctx.storage.put("messages",h);this.broadcast({type:"message:delete",id:d.id});return}
  if(d.type==="reaction"){const m=h.find(x=>x.id===d.id),emoji=String(d.emoji||"").slice(0,8);if(!m||!emoji)return;m.reactions||={};m.reactions[emoji]||=[];const a=m.reactions[emoji],i=a.indexOf(s.user.id);if(i>=0)a.splice(i,1);else if(a.length<100)a.push(s.user.id);await this.ctx.storage.put("messages",h);this.broadcast({type:"message:reaction",id:m.id,reactions:m.reactions})}
 }
 broadcast(d,exclude){const raw=JSON.stringify(d);for(const ws of this.ctx.getWebSockets())if(ws!==exclude&&ws.readyState===WebSocket.OPEN)try{ws.send(raw)}catch{}}
 async webSocketClose(ws){const s=this.sessions.get(ws)||ws.deserializeAttachment();this.sessions.delete(ws);if(s)this.broadcast({type:"presence",action:"offline",user:s.user},ws);try{ws.close()}catch{}}
 async webSocketError(ws){this.sessions.delete(ws)}
}
