(() => {
  const $=s=>document.querySelector(s);
  const api=async(url,opts={})=>{const r=await fetch(url,{credentials:'include',...opts,headers:{'Content-Type':'application/json',...(opts.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok||d.success===false)throw new Error(d.error||`Request failed (${r.status})`);return d};
  const toast=m=>{let t=$('#yprxyToast');if(!t){t=document.createElement('div');t.id='yprxyToast';t.className='toast';document.body.appendChild(t)}t.textContent=m;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),2400)};
  function imageData(file){return new Promise((resolve,reject)=>{if(!file||!file.type.startsWith('image/'))return reject(new Error('Choose an image file'));const r=new FileReader(),i=new Image();r.onload=()=>{i.onload=()=>{const c=document.createElement('canvas');c.width=256;c.height=256;const s=Math.max(256/i.width,256/i.height),w=i.width*s,h=i.height*s,x=(256-w)/2,y=(256-h)/2;c.getContext('2d').drawImage(i,x,y,w,h);resolve(c.toDataURL('image/jpeg',.8))};i.onerror=()=>reject(new Error('Could not read image'));i.src=r.result};r.onerror=()=>reject(new Error('Could not read image'));r.readAsDataURL(file)})}
  function mount(){const emoji=$('#profileEmoji');if(emoji&&!$('#profilePfpFix')){const field=emoji.closest('.field');if(field){field.innerHTML='<label>Profile picture</label><div id="profilePfpFix" style="display:flex;align-items:center;gap:14px"><div id="profilePfpPreview" class="avatar" style="width:78px;height:78px">Y</div><div style="flex:1"><input id="profilePfpFile" type="file" accept="image/*" style="width:100%"><small style="display:block;color:#969dab;margin-top:6px">Upload a JPG, PNG, GIF, or WebP image.</small></div></div>'}}
    const save=$('#saveProfile');if(save&&!save.dataset.profileFix){const clone=save.cloneNode(true);save.replaceWith(clone);clone.dataset.profileFix='1';clone.onclick=async()=>{try{const file=$('#profilePfpFile')?.files?.[0];let avatar='';if(file)avatar=await imageData(file);const d=await api('/api/profile',{method:'POST',body:JSON.stringify({displayName:$('#profileDisplay')?.value||'',avatar,bio:$('#profileBio')?.value||'',accent:$('#profileAccent')?.value||'#5865f2',status:$('#profileStatus')?.value||'online'})});if(window.__yprxyProfileSync)window.__yprxyProfileSync(d.user);const p=d.user?.profile||{};const prev=$('#profilePfpPreview');if(prev&&p.avatar){prev.textContent='';prev.style.background=`url(${JSON.stringify(p.avatar)}) center/cover`};toast('Profile saved ✨')}catch(e){toast(e.message)}}}
  }
  function preview(){const file=$('#profilePfpFile')?.files?.[0];if(!file)return;imageData(file).then(v=>{const p=$('#profilePfpPreview');if(p){p.textContent='';p.style.background=`url(${JSON.stringify(v)}) center/cover`}}).catch(e=>toast(e.message))}
  function init(){mount();$('#profilePfpFile')?.addEventListener('change',preview);setInterval(mount,1000)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
